power = read.csv2("household_power_consumption.txt", header = TRUE, stringsAsFactors = FALSE)
powersub = power[(power$Date == "1/2/2007" | power$Date == "2/2/2007"),]
powersub$Date = as.Date(powersub$Date, format = "%d/%m/%Y")
conc_DT = paste(powersub$Date,powersub$Time,sep=' ')
DT = strptime(conc_DT,"%Y-%m-%d %H:%M:%S")
par(mfcol= c(2,2))
par(mar = c(4,4,2,1))
plot(DT,powersub$Global_active_power, ylab = "Global Active Power (kilowatts)",type = "l", main = NULL, xlab = " ")
plot(DT,powersub$Sub_metering_1, type = "l", ylab = "Energy sub metering", main = NULL, xlab = " ")
lines(DT, powersub$Sub_metering_2, col = "red")
lines(DT, powersub$Sub_metering_3, col = "blue")
legend("topright", col=c('black','red','blue'), legend=c('Sub_metering_1', 'Sub_metering_2','Sub_metering_3'), lty=1, bty='n')
plot(DT,powersub$Voltage, type = "l", ylab = "Voltage", xlab = "datetime")
plot(DT,powersub$Global_reactive_power, type = "l", ylab = "Global_reactive_power", xlab = "datetime")
